---
"dataset": "INTERACTION-Dataset-DR-v1_1"

"temporal":
  "horizon": 6 # s
  "dt": 100 # ms (step-width)
  # N is calculated automatically; int(horizon / dt)

"localization":
  "position_sigma_longitudinal": 2
  "position_sigma_lateral": 0.5
  "position_cross_correlation": 0.0
  "velocity_sigma_longitudinal": 1
  "velocity_sigma_lateral": 0.2
  "velocity_cross_correlation": 0.0

"perception":
  "position_sigma_longitudinal": 2
  "position_sigma_lateral": 0.5
  "position_cross_correlation": 0.0
  "velocity_sigma_longitudinal": 1
  "velocity_sigma_lateral": 0.2
  "velocity_cross_correlation": 0.0
  "egoVehicle_sensors":
    - [15.0, 165.0, 40.0, 0.8]
    - [0.0, 359.9, 10.0, 0.8]
    - [250.0, 290.0, 25.0, 0.8]
  "otherVehicle_sensors":
    - [30.0, 150.0, 30.0, 0.8]

"understanding":
  "type": "basic"

"prediction":
  "multi_modal": False
  "politeness_factor": 0.5
  "deceleration_comfortable": -5.0
  "deceleration_maximum": -8.0
  "acceleration_maximum": 2.5
  "deceleration_comfortable_host": -3.0
  "type": "pseudo"

"decision_making":
  "astar_initialization": False
  "type": "basic"

"planning":
  "computation_time": 400 # ms
  "speed_desired": 11.0 # m/s
  "distance2static_obs": 1.0 # m
  "v2v_safety_dist": 6.0 # m
  "override_max_deceleration": True
  "max_deceleration": 9.0
  "initialization_astar": False
  "type": "constant_velocity"
